In [4]:
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import seaborn as sns

In [5]:
df = pd.read_csv(r'C:\Users\Lenovo\Downloads\prashant.csv')

In [9]:
df.rename(columns={'PM 2.5' : 'PM'}, inplace=True)
df.head()

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0

In [11]:
df.isnull().sum()

Stn Code                            0
Sampling Date                       0
State                               0
City                                0
Location of Monitoring Station      0
Agency                              0
Type of Location                    0
SO2                                 0
NO2                                 0
RSPM/PM10                           0
PM                                332
dtype: int64

In [12]:
df['PM']=df['PM'].replace(np.nan,0)
df.isna().sum()

Stn Code                          0
Sampling Date                     0
State                             0
City                              0
Location of Monitoring Station    0
Agency                            0
Type of Location                  0
SO2                               0
NO2                               0
RSPM/PM10                         0
PM                                0
dtype: int64

In [13]:
df.PM.first_valid_index()

0

In [14]:
df.head()

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0

In [15]:
df.rename(columns={'Location of Monitoring Station ':'Location'},inplace=True)

In [16]:
df.head()

,Stn Code,Sampling Date,State,City,Location of Monitoring Station,Agency,Type of Location,SO2,NO2,RSPM/PM10,PM
0,68,02-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,11,24,143,102.0
1,68,06-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,23,133,96.0
2,68,09-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,8,25,125,116.0
3,68,13-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,10,25,137,107.0
4,68,16-01-15,Odisha,Talcher,"T.T.P.S.Colony, Talcher",Odisha State Pollution Control Board,Industrial Area,9,26,186,118.0